### ISSUE TITLE
Issue in Recorder.delete()

### ISSUE THREAD

**Issue by Whadup** [WarBean/hyperboard#1]
delete() in recorder is called wrong: it submits a single name, but the method expects a list of names. This results in the method iterating over the characters of the name instead of iterating over all names in the list.

See the following patch:

From 40ad2469603f00d43656eb4b8dc5224530d65e75 Mon Sep 17 00:00:00 2001
From: Whadup <a.b@c.edu>
Date: Tue, 31 Jan 2017 14:36:40 +0100
Subject: [PATCH] fix delete() in recorder

---
 hyperboard/recorder.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/hyperboard/recorder.py b/hyperboard/recorder.py
index aaa72df..36e3756 100644
--- a/hyperboard/recorder.py
+++ b/hyperboard/recorder.py
@@ -36,7 +36,7 @@ class Recorder:
         name = md5.hexdigest()
         if name in self.name2series:
             if overwrite:
-                self.delete(name)
+                self.delete([name])
             else:
                 return '<fail>'
         self.name2series[name] = {
-- 
2.3.8 (Apple Git-58)`

**Comment by WarBean** [comment]
Thanks for correction! Already committed the fix.
