### ISSUE TITLE
using with c++

### ISSUE THREAD

**Issue by vrodionovpro** [WarBean/hyperboard#3]
Hi. Nice program and I want to use it with dlib and c++. How I can do it fast as I can.

I think there are 2 options: 
-connect to server with c++ (using curl for example). But I need protocol in this case.
-save files with data. In this case I need format and place to saving.

**Comment by WarBean** [comment]
I recommend option 1. You only need to re-implement the `register` and `append` APIs in [agent.py](https://github.com/WarBean/hyperboard/blob/master/hyperboard/agent.py).
