### ISSUE TITLE
How to switch on/off hyperboard?

### ISSUE THREAD

**Issue by YanWang2014** [WarBean/hyperboard#4]
I mean, in debug phases, i want to disable the hyperboard so that nothing is recorded. Is there any easy way to do so except commenting the codes?
Thank you!

**Comment by WarBean** [comment]
Unfortunately I didn't provide this feature. If you don't want your old records to be overwritten by your debugging records, you can specifically add a "hyperparameter" named `debug` and set it to `False` while training / `True` while debugging.

**Comment by YanWang2014** [comment]
Thank you!
